// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ThoQ60P3cG6rsf7R6INtEUF8ctzbun4',
    appId: '1:866660367953:web:6b8a3a6ca42710e8f34270',
    messagingSenderId: '866660367953',
    projectId: 'flutter-firebase-auth-d8eee',
    authDomain: 'flutter-firebase-auth-d8eee.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-d8eee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1v9plguS7MKsuE0-9dJEFkFEqTP2fqoM',
    appId: '1:866660367953:android:192aa86ab3093caef34270',
    messagingSenderId: '866660367953',
    projectId: 'flutter-firebase-auth-d8eee',
    storageBucket: 'flutter-firebase-auth-d8eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosjovW8W7iStq2MR_5hCzeg88aQLs0ag',
    appId: '1:866660367953:ios:876f97c8b6a4043df34270',
    messagingSenderId: '866660367953',
    projectId: 'flutter-firebase-auth-d8eee',
    storageBucket: 'flutter-firebase-auth-d8eee.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0ThoQ60P3cG6rsf7R6INtEUF8ctzbun4',
    appId: '1:866660367953:web:7cc8b985dd09a8fcf34270',
    messagingSenderId: '866660367953',
    projectId: 'flutter-firebase-auth-d8eee',
    authDomain: 'flutter-firebase-auth-d8eee.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-d8eee.firebasestorage.app',
  );
}
